apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: eduyaginuma/gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # --> NOVO: reservas e limites de CPU / memória
          resources:
            requests:
              cpu: "100m"        # 0,1 vCPU reservado
              memory: "128Mi"
            limits:
              cpu: "500m"        # até 0,5 vCPU
              memory: "512Mi"
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOST
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer          # <- mude de ClusterIP para LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
